vNum1 = int(input('Digite um Numero:'))
vNum2 = int(input('Digite o Segundo Numero:'))
vAdi = (vNum1 + vNum2)
vMult = (vNum1 * vNum2)
vSub = (vNum1 - vNum2)
vDiv = (vNum1 / vNum2)
vEspo = (vNum1 ** vNum2)
vDivInt = (vNum1 // vNum2)
vDivEspo = (vNum1 % vNum2)
print ('A Soma é {} o Produto é {} a Divisão é {:.5f}'.format(vAdi,vMult,vDiv), end=' 5 ')
print ('A esponencia é {} a Divisão Inteira é {} a Divisão espônencial é {}'.format(vEspo,vDivInt,vDivEspo))